< {%
    import {randomCrc32String} from "./utilities.js";
    request.variables.set("id", randomCrc32String());
%}
POST http://172.27.7.211/
Content-Type: application/json

{
    "method": "ping",
    "id": "{{id}}"
}